openapi: 3.0.3
info:
  version: 5.0.0
  title: Open Education API
  description: "OpenAPI (fka Swagger) specification for the Open Education API.\n<br/>\nNOTE:This is a subset of the OOAPI that is used in the \"MBO-Toetsafname\" project (sponsored by mbo-digitaal in the netherlands). This porject uses the \"NL-TEST-ADMIN\" consumer \n<br/>\n<figure>\n\t<a target=\"_blank\" href=\"OOAPIv5_model.png\">\n  <img src=\"OOAPIv5_model.png\" alt=\"OOAPI information model that feeds OOAPI specification\" width=\"70%\" class=\"img-responsive\">\n  </a>\n  <figcaption> O[...]"
  x-logo:
    url: ../logo.png
servers:
  - url: http://demo01.eduapi.nl/v5
    description: SURF demo implementation
tags:
  - name: associations
    description: |
      The associations API provides information about the association between an offering and a person (e.g. students, lecturers, etc).
      Associations can be posted between institutions This requires information details on the offering and the persons.
      To allow for this information a complete person object and offering object can be part of the API.
      The structure is explained in the following model:
      <table>
        <tr>
         <td></td>
         <td colspan=3 align=center>offering</td>
        </tr>
        <tr>
         <td rowspan=3>student</td>
         <td></td>
         <!-- <td>internal</td>
         -->
         <td>external</td>
        </tr>
        <tr>
         <td>internal</td>
         <!-- <td>POST <a href="#tag/offerings/paths/~1offerings~1{offeringId}~1associations~1external/post">/offerings/{offeringId}/associations/me</a> local enrollment based on selected offering
          This call will allow for a local student using his .wellknown credentials to enroll for the offering identified by the offeringId
          <br>Alternatively the association can also be created through POST <a href="#tag/associations/paths/~1associations~1me/post">/associations/me</a>
         </td>
         -->
         <td>POST <a href="#tag/associations/paths/~1associations~1external~1me/post">/associations/external/me</a> gets student details from .wellknown at home institution. It passes offering details (provided by external institution) to the home institution so the home institution can create a placeholder for the offering and its results.
         </td>
        </tr>
        <tr>
         <td>external</td>
          <!--
          <td>
          This method is not yet implemented it requires full student details and offering details. This would mean the
          OOAPI message would contain more than one resource in the message. At the moment the student mobility project is looking into
          a sollution.
          <br> Alternatively it could be achieved through using two calls:
          <ul>
           <li>create student with POST <a href="#tag/persons/paths/~1persons~1{personId}/post">/persons</a></li>
           <li><a href="#tag/offerings/paths/~1offerings~1{offeringId}~1associations~1external/post">/offerings/{offeringId}/associations/me</a></li>
          </ul>
          for the enrollment
         </td>
          -->
         <td>no support needed</td>
        </tr>
      </table>
      Direct update of current information: <a href="#tag/associations/paths/~1associations~1{associationId}/patch"> PATCH /associations/{associationId}</a>
      This call is currently limited to passing results and a remote state. For future use other association resource information could be passed.
      More information on the support for student mobility can be found
      <a href="https://swimlanes.io/d/s5mfpj7Si">here</a>
  - name: components
    description: The components API provides information about components being part of parent courses.
  - name: groups
    description: The groups API provides information about groups that are related to organizations, persons and offerings. Groups of students that are related to an offering are typically used for rostering. The rostering application assigns students based on these groups. For example, class 1b will be assigned to the course offering on monday morning. Not all groups are related to an offering. A group of people can also be a team that is working on a task outside the OOAPI scope. These can be [...]
  - name: offerings
    description: The offerings API provides information about offerings which have a global timeframe, e.g. a period to which students can enroll.
  - name: organizations
    description: The organizations API provides the organizations that are responsible for the execution and recognition of education.
  - name: persons
    description: The persons API provides information about persons related to an organization.
  - name: documents
    description: The documments API provides access to the documents in a binary format
  - name: program_model
    x-displayName: Program
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Program" />
  - name: component_model
    x-displayName: Component
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Component" />
  - name: program_offering_model
    x-displayName: ProgramOffering
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ProgramOffering" />
  - name: course_offering_model
    x-displayName: CourseOffering
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/CourseOffering" />
  - name: component_offering_model
    x-displayName: ComponentOffering
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ComponentOffering" />
  - name: association_model
    x-displayName: Association
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/AssociationFull" />
  - name: person_model
    x-displayName: Person
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Person" />
  - name: group_model
    x-displayName: Group
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Group" />
  - name: organization_model
    x-displayName: Organization
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Organization" />
paths:
  /persons/{personId}:
    get:
      summary: GET /persons/{personId}
      operationId: listPersonById
      description: Get a single person.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - persons
  /organizations/{organizationId}:
    get:
      summary: GET /organizations/{organizationId}
      operationId: listOrganizationById
      description: Get a single organization.
      tags:
        - organizations
  /components/{componentId}:
    get:
      summary: GET /components/{componentId}
      operationId: listComponentById
      description: Get a single component.
      security:
        - oAuthFlows:
            - test-content-flow
            - test-admin-flow
      tags:
        - components
  /components:
    get:
      summary: GET /components
      operationId: listComponents
      description: Get a list of all components, ordered by name (ascending).
      security:
        - oAuthFlows:
            - test-admin-flow
            - test-content-flow
      tags:
        - components
  /components/{componentId}/offerings:
    get:
      summary: GET /components/{componentId}/offerings
      operationId: listOfferingsByComponentId
      description: Get a list of all offerings for this component, ordered chronologically.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
  /offerings:
    get:
      summary: GET /offerings
      operationId: listOfferings
      description: Get a list of all offerings, ordered chronologically.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
  /offerings/{offeringId}:
    get:
      summary: GET /offerings/{offeringId}
      operationId: listOfferingById
      description: Get a single offering.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
    patch:
      summary: PATCH /offerings/{offeringId}
      operationId: partialUpdateOfferingById
      description: |
        PATCH update a single offering based on the offeringID provided. 
      security:
        - openId:
            - offerings.write
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
    put:
      summary: PUT /offerings/{offeringId}
      operationId: replaceOfferingById
      description: |
        PUT / create an offering  or update a single offering based on the offeringID provided. 
        You want to PUT a resource to the same URI you intend to GET it from. also check RFC 72314.3.4 PUT.
      security:
        - openId:
            - offerings.write
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
  /offerings/{offeringId}/associations:
    get:
      summary: GET /offerings/{offeringId}/associations
      operationId: listAssociationsByOfferingId
      description: Get a list of all offering associations.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /documents/{documentId}:
    get:
      summary: GET /documents/{documentId}
      operationId: listDocumentById
      description: Get the binary data from a document.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - documents
  /associations/{associationId}:
    get:
      summary: GET /associations/{associationId}
      description: |
        Get a single association.
      operationId: listAssociationById
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
    patch:
      summary: PATCH /associations/{associationId}
      operationId: partialUpdateAssociationById
      description: |
        Update the status or result of an enrollment. Other elements of the association object COULD 
        also be PATCHED. But are not likely and have therefor not been included in this endpoint.
        Implementation of the PATCH activity is based on use PATCH with JSON Merge Patch standard, 
        a specialized media type `application/merge-patch+json` for partial resource representation 
        to update parts of resource objects.
      security:
        - openId:
            - associations.write
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
    put:
      summary: PUT /associations/{associationId}
      description: |
        PUT a single association to enroll a person on s specific association that can later be retreived. The offeringId is provided in the path. 
      operationId: replaceAssociationById
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /associations/{associationId}/url:
    get:
      summary: GET /associations/{associationId}/url
      description: |
        Get the URL of an association.
      operationId: listAssociationUrl
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /groups:
    get:
      summary: GET /groups
      operationId: listGroups
      security:
        - oAuthFlows:
            - test-admin-flow
      description: Get a list of all groups, ordered by name (ascending).
      tags:
        - groups
  /groups/{groupId}:
    get:
      summary: GET /groups/{groupId}
      operationId: listGroupById
      security:
        - oAuthFlows:
            - test-admin-flow
      description: Get a single group.
      tags:
        - groups
  /groups/{groupId}/persons:
    get:
      summary: GET /groups/{groupId}/persons
      operationId: listPersonsByGroupId
      security:
        - oAuthFlows:
            - test-admin-flow
      description: Get an ordered list of all persons that are member of a given group, ordered by personId.
      tags:
        - groups
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.nl/.well-known/openid-configuration
    oAuthFlows:
      type: oauth2
      description: |
        This API uses oauth Cleint credentials for server to server #/components/schemas/EducationSpecification
      flows:
        clientCredentials:
          tokenUrl: https://example.nl/oauth2/authorize
          scopes:
            test-admin-flow: functions needed to allow the transfer of enrollments, persons and offerings between systems in MBO
x-tagGroups:
  - name: Requests and responses
    tags:
      - associations
      - components
      - groups
      - documents
      - offerings
      - persons
  - name: Models
    tags:
      - association_model
      - component_model
      - component_offering_model
      - course_offering_model
      - group_model
      - person_model
      - program_model
      - program_offering_model
