openapi: 3.0.3
info:
  version: 5.0.0
  title: Open Education API
  description: "OpenAPI (fka Swagger) specification for the Open Education API.\n<br/>\nNOTE:This is a subset of the OOAPI that is used in the \"MBO-Toetsafname\" project (sponsored by mbo-digitaal in the netherlands) \n<br/>\n<figure>\n\t<a target=\"_blank\" href=\"OOAPIv5_model.png\">\n  <img src=\"OOAPIv5_model.png\" alt=\"OOAPI information model that feeds OOAPI specification\" width=\"70%\" class=\"img-responsive\">\n  </a>\n  <figcaption> OOAPI information model that feeds OOAPI specificat[...]"
  x-logo:
    url: ../logo.png
servers:
  - url: http://demo01.eduapi.nl/v5
    description: SURF demo implementation
tags:
  - name: associations
    description: |
      The associations API provides information about the association between an offering and a person (e.g. students, lecturers, etc).
      Associations can be posted between institutions This requires information details on the offering and the persons.
      To allow for this information a complete person object and offering object can be part of the API.
      The structure is explained in the following model:
      <table>
        <tr>
         <td></td>
         <td colspan=3 align=center>offering</td>
        </tr>
        <tr>
         <td rowspan=3>student</td>
         <td></td>
         <!-- <td>internal</td>
         -->
         <td>external</td>
        </tr>
        <tr>
         <td>internal</td>
         <!-- <td>POST <a href="#tag/offerings/paths/~1offerings~1{offeringId}~1associations~1external/post">/offerings/{offeringId}/associations/me</a> local enrollment based on selected offering
          This call will allow for a local student using his .wellknown credentials to enroll for the offering identified by the offeringId
          <br>Alternatively the association can also be created through POST <a href="#tag/associations/paths/~1associations~1me/post">/associations/me</a>
         </td>
         -->
         <td>POST <a href="#tag/associations/paths/~1associations~1external~1me/post">/associations/external/me</a> gets student details from .wellknown at home institution. It passes offering details (provided by external institution) to the home institution so the home institution can create a placeholder for the offering and its results.
         </td>
        </tr>
        <tr>
         <td>external</td>
          <!--
          <td>
          This method is not yet implemented it requires full student details and offering details. This would mean the
          OOAPI message would contain more than one resource in the message. At the moment the student mobility project is looking into
          a sollution.
          <br> Alternatively it could be achieved through using two calls:
          <ul>
           <li>create student with POST <a href="#tag/persons/paths/~1persons~1{personId}/post">/persons</a></li>
           <li><a href="#tag/offerings/paths/~1offerings~1{offeringId}~1associations~1external/post">/offerings/{offeringId}/associations/me</a></li>
          </ul>
          for the enrollment
         </td>
          -->
         <td>no support needed</td>
        </tr>
      </table>
      Direct update of current information: <a href="#tag/associations/paths/~1associations~1{associationId}/patch"> PATCH /associations/{associationId}</a>
      This call is currently limited to passing results and a remote state. For future use other association resource information could be passed.
      More information on the support for student mobility can be found
      <a href="https://swimlanes.io/d/s5mfpj7Si">here</a>
  - name: components
    description: The components API provides information about components being part of parent courses.
  - name: offerings
    description: The offerings API provides information about offerings which have a global timeframe, e.g. a period to which students can enroll.
  - name: persons
    description: The persons API provides information about persons related to an organization.
  - name: component_model
    x-displayName: Component
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Component" />
  - name: component_offering_model
    x-displayName: ComponentOffering
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/ComponentOffering" />
  - name: association_model
    x-displayName: Association
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Association" />
  - name: person_model
    x-displayName: Person
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Person" />
x-tagGroups:
  - name: Requests and responses
    tags:
      - associations
      - components
      - offerings
      - persons
  - name: Models
    tags:
      - association_model
      - component_model
      - component_offering_model
      - person_model
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.nl/.well-known/openid-configuration
    oAuthFlows:
      type: oauth2
      description: |
        This API uses oauth Cleint credentials for server to server #/components/schemas/EducationSpecification
      flows:
        clientCredentials:
          tokenUrl: https://example.nl/oauth2/authorize
          scopes:
            test-admin-flow: functions needed to allow the transfer of enrollments, persons and offerings between systems in MBO
paths:
  /:
    get:
      summary: GET /
      description: Get metadata for the service.
      tags:
        - service metadata
  /persons:
    get:
      summary: GET /persons
      security:
        - oAuthFlows:
            - test-admin-flow
      description: Get an ordered list of all persons.
      tags:
        - persons
    post:
      summary: POST /persons
      description: POST a single person.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - persons
  /persons/{personId}:
    get:
      summary: GET /persons/{personId}
      description: Get a single person.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - persons
  /persons/{personId}/associations:
    get:
      summary: GET /persons/{personId}/associations
      description: Get a list of all associations for an individual person.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /organizations:
    get:
      summary: GET /organizations
      description: Get an ordered list of all organizations, ordered by name.
      tags:
        - organizations
  /organizations/{organizationId}:
    get:
      summary: GET /organizations/{organizationId}
      description: Get a single organization.
      tags:
        - organizations
  /organizations/{organizationId}/programs:
    get:
      summary: GET /organizations/{organizationId}/programs
      description: Get an ordered list of all programs for a given organization, ordered by name.
      tags:
        - organizations
  /organizations/{organizationId}/courses:
    get:
      summary: GET /organizations/{organizationId}/courses
      description: Get an ordered list of all courses for a given organization, ordered by name.
      tags:
        - organizations
  /organizations/{organizationId}/components:
    get:
      summary: GET /organizations/{organizationId}/components
      description: Get an ordered list of all components for a given organization, ordered by name.
      tags:
        - organizations
  /organizations/{organizationId}/offerings:
    get:
      summary: GET /organizations/{organizationId}/offerings
      description: Get a list of all offerings for a given organization
      tags:
        - organizations
  /organizations/{organizationId}/groups:
    get:
      summary: GET /organizations/{organizationId}/groups
      description: Get an ordered list of all groups for a given organization, ordered by name.
      tags:
        - organizations
  /organizations/{organizationId}/education-specifications:
    get:
      summary: GET /organizations/{organizationId}/education-specifications
      description: Get an ordered list of all EducationSpecifications for a given organization, ordered by name.
      tags:
        - organizations
  /academic-sessions:
    get:
      summary: GET /academic-sessions
      description: Get a list of all academic sessions, ordered chronologically.
      tags:
        - academic sessions
  /academic-sessions/{academicSessionId}:
    get:
      summary: GET /academic-sessions/{academicSessionId}
      description: Get a single academic session.
      tags:
        - academic sessions
  /academic-sessions/{academicSessionId}/offerings:
    get:
      summary: GET /academic-sessions/{academicSessionId}/offerings
      description: Get a list of all offerings during this academic session
      tags:
        - academic sessions
  /programs:
    get:
      summary: GET /programs
      description: Get an ordered list of all programs, ordered by name.
      tags:
        - programs
  /programs/{programId}:
    get:
      summary: GET /programs/{programId}
      description: Get a single program.
      tags:
        - programs
  /programs/{programId}/programs:
    get:
      summary: GET /programs/{programId}/programs
      description: Get an ordered list of nested programs, ordered by name.
      tags:
        - programs
  /programs/{programId}/courses:
    get:
      summary: GET /programs/{programId}/courses
      description: Get an ordered list of all courses given through this program.
      tags:
        - programs
  /programs/{programId}/offerings:
    get:
      summary: GET /programs/{programId}/offerings
      description: Get a list of all offerings for this program, ordered chronologically.
      tags:
        - programs
  /courses:
    get:
      summary: GET /courses
      description: Get a list of all courses, ordered by name (ascending).
      tags:
        - courses
  /courses/{courseId}:
    get:
      summary: GET /courses/{courseId}
      description: Get a single course.
      tags:
        - courses
  /courses/{courseId}/components:
    get:
      summary: GET /courses/{courseId}/components
      description: Get an ordered list of all course components.
      tags:
        - courses
  /courses/{courseId}/offerings:
    get:
      summary: GET /courses/{courseId}/offerings
      description: Get a list of all offerings for this course, ordered chronologically.
      tags:
        - courses
  /components/{componentId}:
    get:
      summary: GET /components/{componentId}
      description: Get a single component.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - components
  /components/{componentId}/offerings:
    get:
      summary: GET /components/{componentId}/offerings
      description: Get a list of all offerings for this component, ordered chronologically.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
  /offerings/{offeringId}:
    get:
      summary: GET /offerings/{offeringId}
      description: Get a single offering.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
    patch:
      summary: PATCH /offerings/{offeringId}
      description: |
        PATCH update a single offering based on the offeringID provided. 
      security:
        - openId:
            - offerings.write
        - oAuthFlows:
            - test-admin-flow
      tags:
        - offerings
    put:
      summary: PUT /offerings/{offeringId}
      description: |
        PUT / create an offering  or update a single offering based on the offeringID provided. 
        You want to PUT a resource to the same URI you intend to GET it from. also check RFC 72314.3.4 PUT.
      security:
        - openId:
            - offerings.write
        - oAuthFlows:
            - test-admin-flow  tags: null
        - offerings
  /offerings/{offeringId}/associations:
    get:
      summary: GET /offerings/{offeringId}/associations
      description: Get a list of all offering associations.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /offerings/{offeringId}/associations{associationId}:
    put:
      summary: PUT offerings/{offeringId}/associations/{associationId}
      description: |
        PUT a single association to enroll a person on s specific association that can later be retreived. The offeringId is provided in the path. 
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /offerings/{offeringId}/groups:
    get:
      summary: GET /offerings/{offeringId}/groups
      description: Get an ordered list of all groups related to an offering, ordered by name.
      tags:
        - groups
  /associations/{associationId}:
    get:
      summary: GET /associations/{associationId}
      description: |
        Get a single association.
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
    patch:
      summary: PATCH /associations/{associationId}
      description: |
        Update the status or result of an enrollment. Other elements of the association object COULD 
        also be PATCHED. But are not likely and have therefor not been included in this endpoint.
        Implementation of the PATCH activity is based on use PATCH with JSON Merge Patch standard, 
        a specialized media type `application/merge-patch+json` for partial resource representation 
        to update parts of resource objects.
      security:
        - openId:
            - associations.write
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
    put:
      summary: PUT associations/{associationId}
      description: |
        PUT a single association to enroll a person on s specific association that can later be retreived. The offeringId is provided in the path. 
      security:
        - oAuthFlows:
            - test-admin-flow
      tags:
        - associations
  /buildings:
    get:
      summary: GET /buildings
      description: Get a list of all buildings, ordered by name (ascending).
      tags:
        - buildings
  /buildings/{buildingId}:
    get:
      summary: GET /buildings/{buildingId}
      description: Get a single building.
      tags:
        - buildings
  /buildings/{buildingId}/rooms:
    get:
      summary: GET /buildings/{buildingId}/rooms
      description: Get a list of all rooms in a building.
      tags:
        - buildings
  /rooms:
    get:
      summary: GET /rooms
      description: Get a list of all rooms, ordered by name (ascending).
      tags:
        - rooms
  /rooms/{roomId}:
    get:
      summary: GET /rooms/{roomId}
      description: Get a single room.
      tags:
        - rooms
  /news-feeds:
    get:
      summary: GET /news-feeds
      description: Get a list of all news feeds, ordered by title.
      tags:
        - news
  /news-feeds/{newsFeedId}:
    get:
      summary: GET /news-feeds/{newsFeedId}
      description: Get a single news feed.
      tags:
        - news
  /news-feeds/{newsFeedId}/news-items:
    get:
      summary: GET /news-feeds/{newsFeedId}/news-items
      description: Get an ordered list of all news items.
      tags:
        - news
  /news-items/{newsItemId}:
    get:
      summary: GET /news-items/{newsItemId}
      description: Get a single news item.
      tags:
        - news
  /education-specifications:
    get:
      summary: GET /education-specifications
      description: Get a list of all education specifications, ordered by name (ascending).
      tags:
        - education specifications
  /education-specifications/{educationSpecificationId}:
    get:
      summary: GET /education-specifications/{educationSpecificationId}
      description: Get a single education specification.
      tags:
        - education specifications
  /education-specifications/{educationSpecificationId}/education-specifications:
    get:
      summary: GET /education-specifications/{educationSpecificationId}/education-specifications
      description: Get an ordered list of all education-specifications given through this educationspecification.
      tags:
        - education specifications
  /education-specifications/{educationSpecificationId}/courses:
    get:
      summary: GET /education-specifications/{educationSpecificationId}/courses
      description: Get an ordered list of all courses given through this EducationSpecification.
      tags:
        - education specifications
  /education-specifications/{educationSpecificationId}/programs:
    get:
      summary: GET /education-specifications/{educationSpecificationId}/programs
      description: Get an ordered list of all programs for a given education specification, ordered by name.
      tags:
        - education specifications
  /groups:
    get:
      summary: GET /groups
      description: Get a list of all groups, ordered by name (ascending).
      tags:
        - groups
  /groups/{groupId}:
    get:
      summary: GET /groups/{groupId}
      description: Get a single group.
      tags:
        - groups
  /groups/{groupId}/persons:
    get:
      summary: GET /groups/{groupId}/persons
      description: Get an ordered list of all persons that are member of a given group, ordered by personId.
      tags:
        - groups