# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: bundle the seperate yaml files into one large file

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "bundle"
  cancel-in-progress: true


jobs:
  main:
    name: Bundle Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
  

      - name: Use Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: install npx
        run: npm install @redocly/cli -g


      - name: bundle the file
        run: redocly bundle ./specification/v5/spec.yaml -d -o ./specification/ooapiv5_MBO.yaml

      - name: ensure a commit
        run: echo " " >> ./specification/ooapiv5_MBO.yaml

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bundle
      #     path: ./specification/ooapiv5_MBO.yaml

      # - uses: xresloader/upload-to-github-release@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     file: "./specification/ooapiv5_MBO.yaml"
      #     branches: "main"
      #     overwrite: true
      #     default_release_name: "Test release name for main branch"

      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add  ./specification/ooapiv5_MBO.yaml
          git commit -m "./specification/ooapiv5_MBO.yaml"
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true


