name: Sync Branch to Dev Repo

on:
 # Trigger this workflow only on updates to the 1.1 branch
  push:
    branches: [“v1.1”] 

jobs:
  sync-to-dev-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out Repo 
      - name: Checkout Repo 
        uses: actions/checkout@v3
        with:
          ref: v1.1  # Ensure it checks out the 1.1 branch

      # Step 2: Push changes to DEV Repo 
      - name: Push to DEV Repo 
        env:
          DEV_REPO_URL: https://github.com/<your-username>/<repo-b>.git
          DEV_REPO_TOKEN: ${{ secrets.DEV_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add DEV Repo as a remote
          git remote add dev-repo $DEV_REPO_URL
          
          # Push to the main branch of Repo B
          git push dev-repo v1.1:main --force
